config/routes.rb
Rails.application.routes.draw do

  root to: "static#index"

  devise_for :users
  get "widget/profile/:id", to: "users#widget", as: "user_profile_widget"
  get "profile/:id", to: "users#show", as: "user_profile"
end

app/models/concerns/tokenable.rb
module Tokenable
  extend ActiveSupport::Concern

  included do
    before_create :generate_token
  end

  protected

  def generate_token
    self.guid = loop do
      random_token = SecureRandom.hex(4)
      break random_token unless self.class.exists?(guid: random_token)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  include Tokenable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :assign_level

  def assign_level
    self.level = rand(0..10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :allow_iframe_requests
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def allow_iframe_requests
    response.headers.delete('X-Frame-Options')
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :current_password, :password_confirmation, :name, :cover_photo, :avatar, :description) }
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



  def index
  end

  def show
  end

  def widget
    user = User.find_by_guid(params[:id])
    if user.blank?
      render "templates/widgets/profile-404", layout: "widget"
    else
      render partial: "templates/widgets/profile", locals: { user: user }, layout: "widget"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ==========================================
  #
  # Helpers
  #
    def current_page
      params["controller"] + "#" + params["action"]
    end

    # ======
    #
    # Body class
    #
    # Usage:
    # adds the controller-action to allow for specific page targeting in css/js.
    # TARGET SPARINGLY - css styles should be component based and not dependant on pages
    #
    def friendly_current_page
      begin
        params["controller"] + "-" + params["action"]
      rescue
        "example-app"
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def avatar(user)
    if user.avatar.present?
      image_tag(user.avatar, class: "widget-meta profile-avatar")
    else
      image_tag("https://pbs.twimg.com/profile_images/575994177843904512/Su6OblHX_400x400.jpeg", class: "widget-meta profile-avatar")
    end
  end

  def cover_photo(user)
    if user.cover_photo.present?
      image_tag(user.cover_photo)
    else
      image_tag("http://31.media.tumblr.com/85d20081f45167cfa0444db23df1f0d5/tumblr_mi6ul42CIl1race41o1_500.gif")
    end
  end

end

app/views/layouts/_widget.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThirdPartyJs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'widget', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= friendly_current_page %>">
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThirdPartyJs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'widget', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= friendly_current_page %>">

<%= render partial: "templates/header" %>
<div class="row">
  <div class="medium-12 columns">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </div>
</div>
<%= yield %>
<% #= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/layouts/widget.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThirdPartyJs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'widget', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= friendly_current_page %>">
  <%= yield %>
</body>
</html>

app/views/templates/_header.html.erb
<header class="row">
  <div class="medium-6 columns">
    <h1 class="logo"><a href="/">Tinder <span>for vegans</span></a></h1>
  </div>
  <nav class="medium-6 columns text-right">
    <% if current_user.present? %>
      <%= link_to "My account", edit_user_registration_path() %>
      <hr>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path() %>
      <hr>
      <%= link_to "Register", new_user_registration_path() %>
    <% end %>
  </nav>
</header>

app/views/templates/widgets/_profile.html.erb
<div class="widget profile">
  <div class="widget-header">
    <%= cover_photo(user) %>
  </div>
  <div class="widget-body">
    <div class="profile-header">
      <%= avatar(user) %>

      <div class="widget-meta name ml1"><%= user.name %> <span>Vegan level: <%= user.level %></span></div>
    </div>

    <div class="widget-meta description mb1 mt2"><%= user.description %></div>
    <div class="widget-meta url mb1 mt2">
      <%= link_to user_profile_path(user.guid) do %>
        <i class="fa fa-link mr1"></i> <%= user_profile_url(user.guid) %>
      <%- end %>
    </div>
    <%= link_to "View profile", user_profile_path(user.guid), class: "button button-mini mt1 mb1", target: "_parent" %>
    <%= link_to "<i class='fa fa-heart'></i>".html_safe, user_profile_path(user.guid), class: "button button-mini like ml1", target: "_parent" %>
  </div>
</div>
<%= link_to "Create your own account", new_user_registration_path, class: "mini-link mt1 text-right", target: "_blank" %>
<!-- <a href="http://localhost:3000/register" class="mini-link mt1 text-right" target="_parent">Create your own account</a> -->
<script type="text/javascript">
  (function() {

    $(".mini-link").on("click", function(e){
      e.preventDefault();
      PopupCenter("<%= new_user_registration_url %>" , "Register", 600, 500)
    })
  })();
  function PopupCenter(url, title, w, h) {
    // Fixes dual-screen position                         Most browsers      Firefox
    var dualScreenLeft = window.screenLeft != undefined ? window.screenLeft : screen.left;
    var dualScreenTop = window.screenTop != undefined ? window.screenTop : screen.top;

    width = window.innerWidth ? window.innerWidth : document.documentElement.clientWidth ? document.documentElement.clientWidth : screen.width;
    height = window.innerHeight ? window.innerHeight : document.documentElement.clientHeight ? document.documentElement.clientHeight : screen.height;

    var left = ((width / 2) - (w / 2)) + dualScreenLeft;
    var top = ((height / 2) - (h / 2)) + dualScreenTop;
    var newWindow = window.open(url, title, 'scrollbars=yes, width=' + w + ', height=' + h + ', top=' + top + ', left=' + left);

    // Puts focus on the newWindow
    if (window.focus) {
        newWindow.focus();
    }
  }
</script>

app/views/templates/widgets/profile-404.html.erb
<h2>Could not find that profile.</h2>

app/views/templates/widgets/profile.html.erb
<div class="widget profile">
  <div class="widget-header">
    <%= cover_photo(user) %>
  </div>
  <div class="widget-body">
    <div class="profile-header">
      <%= avatar(user) %>

      <div class="widget-meta name ml1"><%= user.name %> <span>Vegan level: <%= user.level %></span></div>
    </div>

    <div class="widget-meta description mb1 mt2"><%= user.description %></div>
    <div class="widget-meta url mb1 mt2">
      <%= link_to user_profile_path(user.guid) do %>
        <i class="fa fa-link mr1"></i> <%= user_profile_url(user.guid) %>
      <%- end %>
    </div>
    <%= link_to "View profile", user_profile_path(user.guid), class: "button button-mini mt1 mb1", target: "_parent" %>
    <%= link_to "<i class='fa fa-heart'></i>".html_safe, user_profile_path(user.guid), class: "button button-mini like ml1", target: "_parent" %>
  </div>
</div>
<%= link_to "Create your own account", new_user_registration_path, class: "mini-link mt1 text-right", target: "_blank" %>
<!-- <a href="http://localhost:3000/register" class="mini-link mt1 text-right" target="_parent">Create your own account</a> -->
<script type="text/javascript">
  (function() {

    $(".mini-link").on("click", function(e){
      e.preventDefault();
      PopupCenter("<%= new_user_registration_url %>" , "Register", 600, 500)
    })
  })();
  function PopupCenter(url, title, w, h) {
    // Fixes dual-screen position                         Most browsers      Firefox
    var dualScreenLeft = window.screenLeft != undefined ? window.screenLeft : screen.left;
    var dualScreenTop = window.screenTop != undefined ? window.screenTop : screen.top;

    width = window.innerWidth ? window.innerWidth : document.documentElement.clientWidth ? document.documentElement.clientWidth : screen.width;
    height = window.innerHeight ? window.innerHeight : document.documentElement.clientHeight ? document.documentElement.clientHeight : screen.height;

    var left = ((width / 2) - (w / 2)) + dualScreenLeft;
    var top = ((height / 2) - (h / 2)) + dualScreenTop;
    var newWindow = window.open(url, title, 'scrollbars=yes, width=' + w + ', height=' + h + ', top=' + top + ', left=' + left);

    // Puts focus on the newWindow
    if (window.focus) {
        newWindow.focus();
    }
  }
</script>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>